#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running pre-push checks..."
echo "Running tests and build verification before pushing..."
npm run build && npm run manifest && npm run test 